rutas = {
    "B28": ["Portal Américas", "Biblioteca Tintal", "Banderas", "Marsella",
            "Zona Industrial", "CDS - Carrera 32", "La Castellana", "Calle 106",
            "Pepe Sierra", "Prado Veraniego", "Calle 146", "Calle 161", "Portal Norte"],
    "F28": ["Portal Norte", "Calle 161", "Calle 146", "Prado Veraniego", "Pepe Sierra",
            "Calle 106", "La Castellana", "CDS - Carrera 32", "Zona Industrial",
            "Marsella", "Banderas", "Biblioteca Tintal", "Portal Américas"],
    "E32": ["Portal Américas", "Banderas", "CAD", "7 de Agosto", "NQS Calle 75 - Zona M"],
    "B12": ["Portal Sur", "Perdomo", "General Santander", "Comuneros", "Ricaurte",
            "Avenida El Dorado", "Universidad Nacional", "Movistar Arena",
            "NQS Calle 75 - Zona M", "La Castellana", "Calle 100", "Calle 127",
            "Prado Veraniego", "Calle 142", "Toberín", "Portal Norte"],
    "B26": ["Portal Américas", "Biblioteca Tintal", "Transversal 86", "Banderas",
            "Mandalay", "Avenida Américas - Avenida Boyacá", "Héroes", "Calle 85",
            "Virrey", "Calle 100", "Calle 127", "Alcalá"],
    "B10": ["Portal de la 80", "Carrera 90", "Avenida Cali", "Granja - Carrera 77",
            "Boyacá", "Avenida 68", "Carrera 53", "Carrera 47", "Calle 85",
            "Calle 100", "Alcalá", "Calle 146", "Mazurén", "Toberín", "Portal Norte"],
}

segmentos = {
    ("Portal Américas", "Biblioteca Tintal"): 4,
    ("Portal Américas", "Banderas"): 6,
    ("Biblioteca Tintal", "Banderas"): 5,
    ("Biblioteca Tintal", "Transversal 86"): 3,
    ("Transversal 86", "Banderas"): 2,
    ("Banderas", "Mandalay"): 2,
    ("Banderas", "Marsella"): 4,
    ("Banderas", "CAD"): 16,
    ("Mandalay", "Avenida Américas - Avenida Boyacá"): 2,
    ("Marsella", "Zona Industrial"): 5,
    ("Avenida Américas - Avenida Boyacá", "Héroes"): 22,
    ("Zona Industrial", "CDS - Carrera 32"): 3,
    ("CDS - Carrera 32", "La Castellana"): 14,
    ("CAD", "7 de Agosto"): 9,
    ("7 de Agosto", "NQS Calle 75 - Zona M"): 3,
    ("NQS Calle 75 - Zona M", "La Castellana"): 4,
    ("Héroes", "Calle 85"): 2,
    ("Calle 85", "Virrey"): 2,
    ("Calle 85", "Calle 100"): 4,
    ("Virrey", "Calle 100"): 3,
    ("La Castellana", "Calle 100"): 3,
    ("La Castellana", "Calle 106"): 4,
    ("Calle 100", "Calle 127"): 5,
    ("Calle 100", "Alcalá"): 7,
    ("Calle 106", "Pepe Sierra"): 3,
    ("Pepe Sierra", "Prado Veraniego"): 4,
    ("Calle 127", "Prado Veraniego"): 3,
    ("Calle 127", "Alcalá"): 2,
    ("Alcalá", "Calle 146"): 4,
    ("Prado Veraniego", "Calle 142"): 2,
    ("Prado Veraniego", "Calle 146"): 3,
    ("Calle 142", "Toberín"): 4,
    ("Calle 146", "Mazurén"): 2,
    ("Calle 146", "Calle 161"): 3,
    ("Mazurén", "Toberín"): 2,
    ("Toberín", "Portal Norte"): 4,
    ("Calle 161", "Portal Norte"): 3,
    ("Portal Sur", "Perdomo"): 3,
    ("Perdomo", "General Santander"): 6,
    ("General Santander", "Comuneros"): 10,
    ("Comuneros", "Ricaurte"): 3,
    ("Ricaurte", "Avenida El Dorado"): 5,
    ("Avenida El Dorado", "Universidad Nacional"): 3,
    ("Universidad Nacional", "Movistar Arena"): 3,
    ("Movistar Arena", "NQS Calle 75 - Zona M"): 3,
    ("Portal de la 80", "Carrera 90"): 3,
    ("Carrera 90", "Avenida Cali"): 2,
    ("Avenida Cali", "Granja - Carrera 77"): 3,
    ("Granja - Carrera 77", "Boyacá"): 3,
    ("Boyacá", "Avenida 68"): 3,
    ("Avenida 68", "Carrera 53"): 3,
    ("Carrera 53", "Carrera 47"): 2,
    ("Carrera 47", "Calle 85"): 7,
}

tiempos = {}
for (a, b), costo in segmentos.items():
    tiempos.setdefault(a, {})[b] = costo
    tiempos.setdefault(b, {})[a] = costo

PENALIZACION_TRANSBORDO = 10